### ISSUE TITLE
Improvement: Still be able to use the control panels

### ISSUE THREAD

**Issue by staxDB** [iMicknl/LoctekMotion_IoT#7]
It would be awesome if you could still use the control panel. The ESP8266 would have to read the incoming signals from the control panel and pass them on to the control unit. The same applies the other way round: Everything that is read from the control unit should also be written back to the control panel. Would such a setup be possible?

| RJ45 PIN | Original cable color | Ethernet cable color | Description    | ESP8266 GPIO > Control Unit | ESP8266 GPIO > Control Panel | Control Panel  |
|----------|----------------------|----------------------|----------------|-----------------------------|------------------------------|----------------|
| 1        | brown                | white-orange         | RES            |                             |                              | RES            |
| 2        | white                | orange               | SWIM           |                             |                              | SWIM           |
| 3        | purple               | white-green          | N/C            |                             |                              | N/C            |
| 4        | red                  | blue                 | Enable / Awake | D2                          | ?                            | Enable / Awake |
| 5        | green                | white-blue           | RX (of remote) | D6                          | D1                           | TX (of remote) |
| 6        | black                | green                | TX (of remote) | D5                          | D0                           | RX (of remote) |
| 7        | blue                 | white-brown          | GND            |                             |                              | GND            |
| 8        | yellow               | brown                | VDD (5V)       |                             |                              | VDD (5V)       |

The ESP8266 itself could be supplied with power via e.g. USB, so that the control panel could use the power supply from the control unit.

**Comment by iMicknl** [comment]
Have you tried a simple RJ45 splitter? I wonder if that would work as well.. 

Otherwise; it would be interesting to investigate if you can pass through all communication indeed.

**Comment by staxDB** [comment]
I will give it a try

**Comment by NazarLysyi** [comment]
Are you able to connect the panel to the ESP and listen command?

**Comment by dasfuu** [comment]
Isn't that already possible? My desk seems to have two controller ports. Or is that only on specific models?

**Comment by iMicknl** [comment]
@dasfuu my desk also has two controller ports, but unfortunately there are some models with just one controller port. That's the same reason why I haven't spend any time on researching this.

**Comment by Diddlik** [comment]
@staxDB Do you have some progress on this?

**Comment by lordfiSh** [comment]
> Isn't that already possible? My desk seems to have two controller ports. Or is that only on specific models?
@NazarLysyi My [Flexispot E5](https://www.amazon.de/-/en/gp/product/B077JPC7PK/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) has only one Port, Controller Model CB38M2A-1

![image](https://user-images.githubusercontent.com/389680/126472432-0f45eaf4-62e2-4267-8a55-d009d5690a35.png)

**Comment by pepsinio** [comment]
Anyone has success with this? Alternatively i guess an external keypad connected to other GPIO's can do the trick too (minus the display)

**Comment by iMicknl** [comment]
I haven't heard it yet, however feel free to [join us on Discord](https://discord.gg/C7TNzUZ9Xf) to discuss further. I don't think that we have users there yet who only have a single input, however perhaps they have an idea :-).

**Comment by pepsinio** [comment]
@iMicknl you can close this issue with my pull request as well
